server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:10086/eureka
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 20000
  prefix: /api
  routes:
    # 路由到商品的微服务
    item-service: /item/**
    # 路由到搜索微服务
    search-service: /search/**
    # 路由到用户微服务
    user-service: /user/**
